POST http://localhost:8088/rest/auth
Accept: application/json
Authorization: Basic dXNlcjp1c2Vy

###

GET http://localhost:8088/patient/count
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidXNlciIsImV4cCI6MTc0MTk3Mzg2MiwiaWF0IjoxNzQxOTczMjYyLCJzY29wZSI6IlJPTEVfVVNFUiJ9.ALGY82WZjtgq1AbQjQYbNNjgAPl99_AtR_84VYOBfN_oTE-RV2sB5XBjtCDMsYA5OhAzAdt0LG1O9mWr5ZsDtkDGoHMSGmpn80YqbMwCMWZXtbFVSX7ZTPBzV4HDruXsC-r879T4q2dWljEydxVNIy2jqYqPzGa9SJ7PAgXHcQTYxKLw1X2y1C1k7nVIHPjXKSu6fiat6vpC2kbDSrvj2tZWh1I4YFxtHQLYN-fB1BwXl-qzNjEdO9Nndrt2Zv6V6J7ze0eWTGRSEKroBivEXFzOuJC-OGyC5cZmqgdhbdB5f9MDCcuR7p_bPrxzXWkiFTeUi4YY8qn3X7CQgRcaMbvzKNhCkGaRzaJoORsP5yl4j0Ez3ny_O5sWxAy2seMIQimfZ6I0j67XjchXhx1-ql2uawSBVy85BPLB_lhRMIL4m1-UXndTU9UBsXvNCBe3LitIZk2mIgic_P2RmG1XxF2NjxrqaBGmopbk4TmEAOMnZsT7GjkthUyRp4SnbhWvgHWocLzYbATCajhxUI9WNmohJIrOImQui4OMnccNRM9t3FzY94d61UIMUn3GsG-vpXIF_-OaT8WZgy7Bmj_lr5YS7G29RMTCklYh1uz89Q01j2bTCsWW6yLdhIrlA47q0Onch1Yh1XPCfPzgc4mNT2mSBuTXSRLQJlR-eGQtRiA

###

GET http://localhost:8088/patient/count/groupByGender
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidXNlciIsImV4cCI6MTc0MTk3Mzg2MiwiaWF0IjoxNzQxOTczMjYyLCJzY29wZSI6IlJPTEVfVVNFUiJ9.ALGY82WZjtgq1AbQjQYbNNjgAPl99_AtR_84VYOBfN_oTE-RV2sB5XBjtCDMsYA5OhAzAdt0LG1O9mWr5ZsDtkDGoHMSGmpn80YqbMwCMWZXtbFVSX7ZTPBzV4HDruXsC-r879T4q2dWljEydxVNIy2jqYqPzGa9SJ7PAgXHcQTYxKLw1X2y1C1k7nVIHPjXKSu6fiat6vpC2kbDSrvj2tZWh1I4YFxtHQLYN-fB1BwXl-qzNjEdO9Nndrt2Zv6V6J7ze0eWTGRSEKroBivEXFzOuJC-OGyC5cZmqgdhbdB5f9MDCcuR7p_bPrxzXWkiFTeUi4YY8qn3X7CQgRcaMbvzKNhCkGaRzaJoORsP5yl4j0Ez3ny_O5sWxAy2seMIQimfZ6I0j67XjchXhx1-ql2uawSBVy85BPLB_lhRMIL4m1-UXndTU9UBsXvNCBe3LitIZk2mIgic_P2RmG1XxF2NjxrqaBGmopbk4TmEAOMnZsT7GjkthUyRp4SnbhWvgHWocLzYbATCajhxUI9WNmohJIrOImQui4OMnccNRM9t3FzY94d61UIMUn3GsG-vpXIF_-OaT8WZgy7Bmj_lr5YS7G29RMTCklYh1uz89Q01j2bTCsWW6yLdhIrlA47q0Onch1Yh1XPCfPzgc4mNT2mSBuTXSRLQJlR-eGQtRiA
