server:
  port: ${PORT:8088}

app:
  name: Patient Portal Rest API

spring:
  datasource:
    url: jdbc:h2:file:./db/datafile.h2;MODE=PostgreSQL;
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

jwt:
  public-key: classpath:jwt.public.key
  private-key: classpath:jwt.private.key

logging:
  level:
    org:
      atmosphere: warn
      springframework: debug