server:
  port: ${PORT:8080}

app:
  name: Patient Portal

spring:
  mustache:
    check-template-location: false
  datasource:
    url: jdbc:h2:file:./db/datafile.h2;MODE=PostgreSQL;
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

vaadin:
  launch-browser: false

logging:
  level:
    org:
      atmosphere: warn